circle ci issue

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,83 +1,395 @@
-
 version: 2.1
 
 orbs:
-  node: circleci/node@6.1.0
+  shellcheck: circleci/shellcheck@1.2.0
+  snyk: snyk/snyk@1.7.0
+  windows: circleci/windows@5.0.0
 
 executors:
-  linux:
+  go:
     docker:
-      - image: 'codeceptjs/codeceptjs'
+      - image: cimg/go:1.21.5
+    resource_class: large
+    environment:
+      CGO_ENABLED: 0
+  mac:
+    macos:
+      xcode: 15.1.0
+    resource_class: macos.m1.medium.gen1
+    environment:
+      CGO_ENABLED: 0
+      TERM: xterm-256color
 
 commands:
-  install_dependencies:
+  force-http-1:
     steps:
-      - upgrade_node
-      - checkout
-      - node/install-packages:
-          pkg-manager: yarn
-  upgrade_node:
+      - run:
+          # https://app.circleci.com/jobs/github/CircleCI-Public/circleci-cli/6480
+          #     curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
+          # The issue seems to be on the server-side, so force HTTP 1.1
+          name: "cURL: Force HTTP 1.1"
+          command: echo '--http1.1' >> ~/.curlrc
+  build-docker-image:
     steps:
-      - run: node --version
-      - run: apt-get update && apt-get install -y curl
-      - run: curl --version
-      - node/install:
-          node-version: '22.9'
-      - run: node --version
+      - run:
+          name: Build Latest Docker Image
+          command: |
+            docker build -t circleci/circleci-cli:0.1.$CIRCLE_BUILD_NUM .
+            docker run --rm circleci/circleci-cli:0.1.$CIRCLE_BUILD_NUM circleci update check
+  build-alpine-image:
+    steps:
+      - run:
+          name: Build Alpine Docker Image
+          command: |
+            docker build -t circleci/circleci-cli:0.1.$CIRCLE_BUILD_NUM-alpine --file Dockerfile.alpine .
+            docker run --rm circleci/circleci-cli:0.1.$CIRCLE_BUILD_NUM-alpine update check
+  deploy-save-workspace-and-artifacts:
+    steps:
+      - persist_to_workspace:
+          root: .
+          paths:
+            - "dist"
+      - store_artifacts:
+          path: ./dist
+          destination: dist
+  install-goreleaser:
+    parameters:
+      version:
+        type: string
+        default: "1.19.1"
+    steps:
+      - run:
+          name: Install GoReleaser
+          command: |
+            echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
+            sudo apt -q update -y
+            sudo apt -q install -y --no-install-recommends goreleaser=<< parameters.version >>
+  gomod:
+    steps:
+      - restore_cache:
+          keys: ["v3-gomod-{{ arch }}-"]
+      - run:
+          name: Download go module dependencies
+          command: go mod download
+      - save_cache:
+          key: v2-gomod-{{ arch }}-{{ checksum "go.sum" }}
+          paths:
+            - /go/pkg/mod # Linux
+            - ~/go/pkg/mod # macOS
 
 jobs:
-  setup:
-    executor: linux
+  test_windows:
+    executor:
+      name: windows/default
+      shell: bash --login -eo pipefail
     steps:
-      - install_dependencies
+      - run: git config --global core.autocrlf false
+      - checkout
+      - run: mkdir test_results
+
+      - run:
+          name: Run tests
+          command: |
+            export GOBIN=/c/go/bin
+            export PATH=$GOBIN:$PATH
+            go install gotest.tools/gotestsum@latest
+            gotestsum --junitfile test_results/windows.xml
+      - store_test_results:
+          path: test_results
+      - store_artifacts:
+          path: test_results
+  test_mac:
+    executor: mac
+    steps:
+      - checkout
+      - run: |
+          curl -OL https://go.dev/dl/go1.21.5.darwin-arm64.pkg
+          sudo installer -pkg ./go1.21.5.darwin-arm64.pkg -target /
+          echo 'export PATH="/usr/local/go/bin:$PATH"' >> ~/.bash_profile
+      - gomod
+      - run: make test
+  build:
+    executor: go
+    steps:
+      - checkout
+      - gomod
+      - run: make
       - persist_to_workspace:
-          root: ./
+          root: .
           paths:
-            - ./*
-
-  yarn_lint:
-    executor: linux
+            - "build"
+  cucumber:
+    docker:
+      - image: cimg/ruby:2.7
     steps:
-      - upgrade_node
+      - checkout
       - attach_workspace:
-          at: ./
-      - run: yarn lint
+          at: .
+      - run:
+          name: "Install CLI tool from workspace"
+          command: sudo cp ~/project/build/linux/amd64/circleci /usr/local/bin/
+      - run:
+          command: bundle install
+          working_directory: integration_tests
+      - run:
+          command: bundle exec cucumber
+          working_directory: integration_tests
+      - run:
+          name: "Make sure simple command do not cause any timeout"
+          command: circleci version
 
-  yarn_test:
-    executor: linux
+  test:
+    executor: go
     steps:
-      - upgrade_node
-      - attach_workspace:
-          at: ./
-      - run: npx puppeteer browsers install chrome
-      - run: yarn test
+      - checkout
+      - gomod
+      - run: make test
+
+  coverage:
+    executor: go
+    environment:
+      CGO_ENABLED: 1
+    steps:
+      - checkout
+      - force-http-1
+      - gomod
+      - run: make cover
       - store_artifacts:
-          path: ./output
-      - store_test_results:
-         path: tests   
+          path: ./coverage.txt
+          destination: coverage.txt
 
-  yarn_test_parallel:
-    executor: linux
+  docs:
+    executor: go
     steps:
-      - upgrade_node
-      - attach_workspace:
-          at: ./
-      - run: npx puppeteer browsers install chrome
-      - run: yarn test-run-multiple
+      - checkout
+      - run:
+          name: Install pandoc
+          command: |
+            sudo apt-get update
+            sudo apt-get install pandoc
+      - gomod
+      - run: go run main.go usage
       - store_artifacts:
-          path: ./output
-      - store_test_results:
-          path: tests   
+          path: ./docs
+          destination: docs
+      - run: ./.circleci/generate-docs.sh
+      - run: ./.circleci/deploy-gh-pages.sh
+
+  lint:
+    docker:
+      - image: golangci/golangci-lint:v1.51.0-alpine
+    resource_class: large
+    steps:
+      - checkout
+      - run: golangci-lint run
+
+  deploy-test:
+    executor: go
+    steps:
+      - run:
+          name: Skip this job if this is a forked pull request
+          command: |
+            if [ -n "$CIRCLE_PR_NUMBER" ]; then
+              echo "Forked PRs can't run this step."
+              circleci step halt
+            fi
+      - checkout
+      - install-goreleaser
+      - gomod
+      - run:
+          name: Release
+          command: |
+            git config --global user.email $GH_EMAIL
+            git config --global user.name $GH_NAME
+            git tag -a "v0.1.$CIRCLE_BUILD_NUM" -m "Release v0.1.$CIRCLE_BUILD_NUM"
+            goreleaser --skip-publish
+      - setup_remote_docker:
+          docker_layer_caching: true
+      - build-docker-image
+      - build-alpine-image
+      - deploy-save-workspace-and-artifacts
+
+  deploy:
+    executor: go
+    steps:
+      - checkout
+      - install-goreleaser
+      - run:
+          name: Tag Repo
+          command: |
+            git config --global user.email $GH_EMAIL
+            git config --global user.name $GH_NAME
+            git tag -a      "v0.1.$CIRCLE_BUILD_NUM" -m "Release v0.1.$CIRCLE_BUILD_NUM"
+            git push origin "v0.1.$CIRCLE_BUILD_NUM"
+      - gomod
+      - run:
+          name: Release
+          command: goreleaser
+      - setup_remote_docker:
+          docker_layer_caching: true
+      - run:
+          name: Docker Login
+          command: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
+      - build-docker-image
+      - run:
+          name: Deploy Docker Image
+          command: |
+            docker push     circleci/circleci-cli:0.1.$CIRCLE_BUILD_NUM
+            docker tag      circleci/circleci-cli:0.1.$CIRCLE_BUILD_NUM circleci/circleci-cli:latest
+            docker push     circleci/circleci-cli:latest
+      - build-alpine-image
+      - run:
+          name: Deploy Alpine Docker Image
+          command: |
+            docker push     circleci/circleci-cli:0.1.$CIRCLE_BUILD_NUM-alpine
+            docker tag      circleci/circleci-cli:0.1.$CIRCLE_BUILD_NUM-alpine circleci/circleci-cli:alpine
+            docker push     circleci/circleci-cli:alpine
+      - deploy-save-workspace-and-artifacts
+
+  snap:
+    docker:
+      - image: cibuilds/snapcraft:stable
+    steps:
+      - checkout
+      - attach_workspace:
+          at: .
+      - run: |
+          TAG=$(./dist/circleci-cli_linux_amd64_v1/circleci version | cut -d' ' -f 1) && export TAG
+          sed -i -- "s/%CLI_VERSION_PLACEHOLDER%/$TAG/g" snap/snapcraft.yaml
+      - run: snapcraft
+      - run:
+          name: Publish to store
+          command: |
+            # The Snapcraft login file here will expire: 2021-03-05T18:12:13. A new one will need to be created then.
+            mkdir .snapcraft
+            echo $SNAPCRAFT_LOGIN_FILE | base64 --decode --ignore-garbage > .snapcraft/snapcraft.cfg
+            snapcraft push *.snap --release stable
+
+  brew-deploy:
+    executor: mac
+    environment:
+      USER: circleci
+      TRAVIS: circleci
+      DESTDIR: /Users/distiller/dest
+    steps:
+      - checkout
+      - force-http-1
+      - run: |
+          mkdir $DESTDIR
+          curl -fLSs https://circle.ci/cli | DESTDIR="$DESTDIR" bash
+      - run: |
+          git config --global user.email "$GH_EMAIL" > /dev/null 2>&1
+          git config --global user.name "$GH_NAME" > /dev/null 2>&1
+      - run: brew --version
+      - run: brew tap --force homebrew/core
+      - run: ./.circleci/brew-deploy.sh
+
+  chocolatey-deploy:
+    executor: windows/default
+    steps:
+      - checkout
+      - run:
+          working_directory: chocolatey
+          name: Run update script
+          command: .\update-version.ps1
+      - run:
+          command: choco pack circleci-cli\circleci-cli.nuspec
+          working_directory: chocolatey
+      - run:
+          command: copy-item circleci-cli.*.nupkg circleci-cli.nupkg
+          working_directory: chocolatey
+      - run:
+          name: Push to Chocolatey package repository
+          command: choco push circleci-cli.nupkg --source https://chocolatey.org/ --apikey $env:CHOCO_API_KEY
+          working_directory: chocolatey
+
+  vulnerability-scan:
+    executor: go
+    steps:
+      - checkout
+      - run:
+          name: Setup Scanning
+          command: |
+            git config --global url."https://$GITHUB_USER:$GITHUB_TOKEN@github.com/circleci/".insteadOf "https://github.com/circleci/"
+      - when:
+          condition:
+            or:
+              - equal: [main, << pipeline.git.branch >>]
+          steps:
+            - run:
+                name: Launching Snyk Orb Scanning
+                command: echo "Running snyk/scan on main; uploading the results"
+            - run:
+                name: Cleanup RemoteRepoURL
+                command: echo 'export REMOTE_REPO_URL="${CIRCLE_REPOSITORY_URL%".git"}"' >> "$BASH_ENV"
+            - snyk/scan:
+                organization: "circleci-public"
+                fail-on-issues: true
+                severity-threshold: high
+                monitor-on-build: true
+                additional-arguments: "--all-projects --remote-repo-url=${REMOTE_REPO_URL} -d"
+      - unless:
+          condition:
+            or:
+              - equal: [main, << pipeline.git.branch >>]
+          steps:
+            - run:
+                name: Launching Snyk Orb Scanning
+                command: echo "Running snyk/scan on branch; not uploading the results"
+            - snyk/scan:
+                organization: "circleci-public"
+                fail-on-issues: true
+                severity-threshold: high
+                monitor-on-build: false
+                additional-arguments: "--all-projects -d"
+
 workflows:
-  run_tests:
+  ci:
     jobs:
-      - setup
-      - yarn_lint:
+      - build
+      - cucumber:
+          requires: [build]
+      - shellcheck/check:
+          exclude: ./vendor/*
+      - test
+      - test_mac
+      - test_windows
+      - coverage
+      - lint
+      - vulnerability-scan:
+          context: org-global-employees
+      - deploy-test
+      - docs:
           requires:
-            - setup
-      - yarn_test:
+            - deploy
+      - snap:
           requires:
-            - setup
-      - yarn_test_parallel:
+            - deploy
+      - chocolatey-deploy:
           requires:
-            - setup
+            - deploy
+      # Only deploy to homebrew after manual approval.
+      - run-brew-deploy-gate:
+          type: approval
+          requires:
+            - deploy
+      - brew-deploy:
+          requires:
+            - run-brew-deploy-gate
+          context:
+            - devex-release
+      - deploy:
+          requires:
+            - cucumber
+            - test
+            - test_mac
+            - coverage
+            - lint
+            - deploy-test
+            - shellcheck/check
+            - vulnerability-scan
+          filters:
+            branches:
+              only: main
+          context:
+            - devex-release
